### ISSUE TITLE
Ganon

### ISSUE THREAD

**Issue by Dunspartain** [JSsixtyfour/smashremix#103]
Ganon takes no knock back when doing a Warlock Punch, please fix this, and also, there should be a 1-3 variant for the smb 1-1 stage.

**Comment by leodexe** [comment]
That's intended. But honestly the move is pretty easy to telegraph and can simply be grabbed or rolled. Eventually the opponent learns how to deal with it and becomes complete dogshit.

Ganondorf should have Cape instead of Warlock Punch, as Cape would further declone him from Falcon and serve as an aid to his recovery options, which is arguably one of his flaws that retain him in the Low Tier. Cape would also slightly help against projectile users such as Fox/Link who can easily camp Ganondorf due to him being too slow to approach.

Taking a excerpt of Cape from ssbwiki's PM Ganondorf:

"New neutral special: Dead Man's Volley & Drift. Using this move in the air causes him to float for one second, however unlike Peach and Mewtwo he is unable to control his movement after starting, and also gradually loses height. Using it while floating or on the ground will have him flip his cape, reflecting projectiles back at twice their speed and weakly damages nearby opponents with minimal, set knockback. An aerial or jump can be acted out of a float, or it can be simply ended by pressing down. This improves Ganondorf's recovery and his options against projectile users while also giving him aerial mix-ups."

Warlock Punch doesn't do any justice to make this character any competitively better.
