### ISSUE TITLE
Smash Remix playable on hacked Wii U 

### ISSUE THREAD

**Issue by G3K20** [JSsixtyfour/smashremix#22]
Dont know if it is the right place to ask for, but it is possible to play SmashRemix as an injection on a hacked Wii U? If yes can someone explain how and which base rom i need.

Thx.

**Comment by leodexe** [comment]
AFAIK, the Wii U has a vWii Mode which lets you play homebrew and other hacks when you softmod it. In the Wii it is playable with this emulator `https://files.extremscorner.org/wii/apps/mupen64/latest`
Only annoying bug it has is that most of the new custom stages displays as almost full black textures. But I already addressed this issue. Funny thing is that OP mentioned that they won't put effort towards fixing other emulators glitches such as this one, but when released SR version 0.9.2 they unintentionally fixed it so there might be some hope to get all custom stages correctly displayed. If you need help you can reply again but I'll warn you I can only give you help about modding Wii's since I have never softmodded a Wii U but the proccess should be understandable and there are a lot of guides to softmod your Wii U.

**Comment by G3K20** [comment]
Thank you for your answer. My Wii U is softmoded already. On the Wii U is it possible to put Gamecube, Wii and N64 in the Home-Menü like VC Games or Channels.  I know that Smash 64 Injections works fine on the Wii U. So the question was is it possible to got it work, bc i know that some Rom-hacks doesnt work.

**Comment by leodexe** [comment]
Due to technical limitations about file size limit on VC WAD Injection on Wii and Wii U, ROM's that are large than the container itself where the ROM will be placed are impossible to inject. Therefore there is no solution, as I said before, play Smash Remix on Not64 2019-04-10, it works on both Wii and Wii U because they handle the same architecture. The only bug there is the darkened textures on most new custom stages and since some of these stages were optimized they also fixed the dark glitch for the Wii and Wii U, if the devs want to fix this already adressed the issue, they only need to check what change in the stage optimization made it possible to fix the dark texture glitch, and apply that same change to all other non-optimized stages. I don't know about ROM Hacking and I have no idea what I'm saying but in practice it has already been proven to be fixed. So if they are in good mood, we should expect a fix for the dark textured stages glitch that only affects Wii/WiiU on the next patch.

**Comment by jordanbarkley** [comment]
This is not the place to discuss this. You can head over to the Smash Remix discord to discuss this.

That said, we typically do not program changes to make the game emulator compatible. The team is always busy working around fixable emulator bugs takes away valuable from development. 

Jorg

**Comment by leodexe** [comment]
Why not? It is an issue related to the game and it affects an specific console/emulator to begin with, or to be more precise, affects an entire arch (GC/Wii/Wii U aka Dolphin). There aren't any guidelines for reporting bugs, unless you specifically state that bugs should be reported to the Smash Remix Discord, which it was something I wasn't aware, and maybe OP wasn't aware too. It is worth mentioning that there should be a guideline for reporting specific issues in specific areas, just like you said. When we play the game and we, the players found out a bug or a glitch that hinders gameplay, I think it makes sense to report it here in the Issues right here to let devs like you know what's wrong and be aware of that, wether you will ignore it or do something about that it's up to you. You don't need to be rude,

**Comment by leodexe** [comment]
@jordanbarkley

**Comment by jordanbarkley** [comment]
I did not mean to be hostile. The team always appreciate voicing and helping out so I'll elaborate. You may not be completely happy with the answer but I want you to be on the same page.

> It is an issue related to the game
It is not an issue related to the Smash Remix. Smash Remix is specifically targeted at and tested for console compatibility. If it works on console, an emulator could and should be able to emulate the game correctly. Catering to every single emulation option is not a priority for a couple of reasons. Firstly,  Nintendo 64 emulators are almost never accurate. They use hacky methods and workarounds in favor of FPS increase and ease of development. Secondly, they are hard to debug. To find what is causing that issue and then develop a workaround patch for an emulator is time consuming. With several other working options, it is difficult to justify the time spent catering to every emulation option.

> There aren't any guidelines for reporting bugs, unless you specifically state that bugs should be reported to the Smash Remix Discord

I was unaware of this. I'll talk to The_Smashfather about this.

If you'd like to talk about this some more feel free to contact me on Discord. Cyjorg#1065.

Jorg

**Comment by carnage702** [comment]
this is an issue with glide pluggin on wii64/not64

If people here use wii64 1.2 Rice version the game works perfectly on wii or wiiu, if vwii injected you can even use the wiiu gamepad to playit and overclock vwii cpu to get even more speed if needed.

**Comment by leodexe** [comment]
It can get more speed but also you get more lag, Wii has less processing power but at least it doesn't lag. So it's a dilemma of less display lag vs better framerate
https://www.youtube.com/watch?v=Lb8zj5uKifk
