### ISSUE TITLE
Suggestion: Tone down YL's up-b hitbox.

### ISSUE THREAD

**Issue by Monkeor** [JSsixtyfour/smashremix#30]
![image](https://user-images.githubusercontent.com/46661228/84588194-2b19f100-adf3-11ea-8a37-8a25bad69818.png)
Large swaths of empty space regularly hit people on this attack, and the hitboxes cover link almost completely, making it beat out just about every approach aside from very specific angles. It's bananas.

**Comment by leodexe** [comment]
I agree with this. While it is true the hitboxes of YL's UpB should be large enough so the move connnects reliably, naturally it should be able to be Smash DI'ed with relatively ease, since most multihit moves on Smash64 can be DI'ed with pretty ease, rendering them less useful but they still work when used properly. The thing here is that devs seem to be aware of this and made almost every multihit move the new Remix characters has almost twice as hard to escape out. I can't tell if it is because the hitboxes are large enough to prevent any escape with DI or that they simply reduced the threshold of the distance that the SDI grants when those moves are performed, it is obvious that these two moves, the other one being Dark Samus UpB are insanely hard to DI out in comparison with the vanilla Samus counterpart. My suggestion should be that Young Link's UpB should be reworked so all multihits hits reliably but the move should be nerfed with less knockback and thus less KO potential, because even chaining the move into itself at low % is retardedly easy and 100% guaranteed. Also, Young Link's Sword is smaller than Adult Link's Master Sword, so logically it should make sense his sword attacks hitboxes, and specially UpB should have less range than Adult Link sword attack hitboxes.
