### ISSUE TITLE
Kirby powers are missing for new characters

### ISSUE THREAD

**Issue by jridgewell** [JSsixtyfour/smashremix#45]
It seems Kirby can't steal the powers from the new characters, which makes it a bit more difficult to play as him. Is there any plan to add this?

**Comment by philiporlando** [comment]
The devs are extremely adamant about not altering any of the original characters (which is a good thing), however, it makes sense to create a separate version of Kirby (much like the Euro or Japanese version of other characters) so that the players can choose whether they want copy abilities for remix characters or not.

Kirby is at a slight disadvantage when facing remix characters because his copy doesn't work, but I also understand not wanting to overwrite any OG aspects of the game. Being able to toggle between OG and SR versions seems like an appropriate compromise.
