### ISSUE TITLE
Expansion Pak Requirement

### ISSUE THREAD

**Issue by giulianobelinassi** [JSsixtyfour/smashremix#57]
This hack says that it requires the expansion pak. But *why* exactly this is a requirement? Is it possible to optimize this so that this requirement is removed?

I am asking this because I do not own a expansion pak, those turned out to be really expensive where I live.

**Comment by JSsixtyfour** [comment]
No, it is not.

**Comment by giulianobelinassi** [comment]
What is not? The expansion pak requirement? the possibility of removal of the requirement?

And yet, the question about *why* is still unanswered.

**Comment by jtl3d** [comment]
We need the extra ram in order to add all the extra features so the requirement is not going away. Hopefully you find a pak!

**Comment by giulianobelinassi** [comment]
I am sorry to keep bothering with this question, but I was expecting a more technical, verifiable answer. Something like: "We broke that on version X, but we have no idea how to fix it", or "we introduced a feature in version X that requires more RAM", or a DK64 like "there is a memory leak which can be mitigated if player has an expansion pak", or even "we designed this to require the expansion pak from the beginning and therefore we do not know how deep goes the requirement". Depending of the answer, something can be done about it because it is possible to track the source of the issue.

**Comment by jtl3d** [comment]
I understand where you are coming from. You are welcome to review the code and understand the issue at a deeper level. 4gb of RAM is not enough to do the things we do in remix. We have explored options for optimizing RAM already but the fact remains we need the expansion pak. Again, good luck.

**Comment by jtl3d** [comment]
Oops I meant 4mb

**Comment by jordanbarkley** [comment]
There are many reasons why we require the expansion pak.

1. Safety. This is the biggest reason. Messing something up or introducing a game breaking bug is far from ideal. We have user experience and tournament viability in mind always so keeping the game working is a priority.
2. Lack of native malloc. There are no memory leaks in this game because there's no free() and all allocated memory clears every time you leave a screen. This is a design decision made when you're already low on RAM space (as you save space from lacking header data for each chunk of memory allocated) or when you're concerned about frame rate (RCP/DMA loading files right before use takes times leading to frame drops, an issue made even worse when you have to decompress the files on the fly. Funny decompressing all the files would lead to larger ROM which people complain about too!).

Adding things to a game without source optimized for specific hardware (aka optimized to work well on 4 MB) is hard. Like John said, if you'd like to explore, feel free.

**Comment by giulianobelinassi** [comment]
Hi jordanbarkley.

Thank you for your detailed answer. This is the kind of answer that I was expecting and it gives me a background to look for something in the code.

Thank you,
Giuliano.
