### ISSUE TITLE
MetalMario GiantDK handicap lacking

### ISSUE THREAD

**Issue by MaximusChia** [JSsixtyfour/smashremix#82]
Hello, I greet everyone involved on this project and im very thankful for making something was just a dream for years.
I have some requests to have the perect experience on SmashRemix!
At first, I used a gameshark code to give this bosses the extra handicap to make them resistant as on Single Player Mode.
On this version, gamesharks not working on ED 64, just black screen and game not launch.

So I may ask, how make GS codes work on console? In PJ64 they do.
Or, patch these characters to make them as hard as they are meant to be. (Extra Handicap was set to hex 22 via GS) Metal mario
and Giant Dk are pretty useless as they are actually, and not fun.
Third Opttion is to make Handicap modifier be higher than 9. These bosses use 34 (hex 22)
I dont know how to patch otherwise i could try If someone assist me.

**Comment by JSsixtyfour** [comment]
The characters will remain as they are intended without the additional 1p only handicaps.

**Comment by leodexe** [comment]
How can you tell they "are intended" if they were never intended to be playable in vs mode?
You can't tell if they disabled handicap Metal Mario / Giant DK in VS mode because they were testing stuff and they "forgot" to reenable it back before releasing the final version of the game. Anyways, is not like this even matter because as unplayable characters the fact is they probably left them as is because no one would expect someone to make them playable.

What we know, is that they were intended to have handicaps in 1P Mode which serve their purpose as mid-boss characters.
The logical followup is that they SHOULD retain their 1P properties as playable characters in VS Mode, It doesn't make sense to have these joke versions of VS Mode Metal Mario and Giant DK, and even go as far as fixing the fastfall stats on Metal Mario.

It's not about having "original characters", because you know very well the decision making of these guys wasn't bright enough and lots of controversial decisions were taken during the development (like buffing a Top Tier TWICE and nerfing some low tiers)

It's about having functional characters. You should look it's ok to have this mess up of character? I'm looking specifically at Metal Mario and Giant DK, because they were never intended to become playable characters, unlike U-Link which was purposefully nerfed in U, these two guys were made with the bare minimum requirements to be "fighters" if you know what I mean. It's a lazy overview of leaving them "as is" when the final product of these now, playable characters is a complete mess that you even refuse to address properly. While we're at it.

Marth is a pretty example of good character design.

Metal Mario is not good character design, neither Giant DK is.

Hell, I even dare to say Piano is "good" character design compared with these two, despite this thing being a complete joke character.

And these guys are in the same ROM Hack.

Why?

Because no one cares about them enough to give them some love.
