### ISSUE TITLE
Fighting Polygon Team Unbalanced Remix 1P

### ISSUE THREAD

**Issue by TorqueEmPup** [JSsixtyfour/smashremix#92]
They fight far too aggressively for the sheer number of them that you have to kill, even on Normal, and there is not quite enough time to kill them all before the timer runs out.

**Comment by leodexe** [comment]
It's true that any of the strats you would use on Vanilla Polygon Team doesn't work against Remix Polygon team, usually on vanilla 1P I would just take them out quickly before they "wake up" and start approaching and attacking, and in case I fail to kill them before that happens, just go ledge and spam getup attack, that work wonders most of the time. But with Remix 1P it seems not only they are aggresive the very moment they spawn, but they also are slightly more resistant than vanilla so most getup attacks no longer OHKO them, rendering the getup attack strat nearly useless, and because they are instantly aggresive, you're not even safe during the first second of the match which forces you to stall ledge for invulnerability until you figure out a way to knock them out safely.

It seems the AI on all Remix modes was modified to be more aggresive, specially in the stage you mentioned. I'd suggest an option to add a toggle to let the user choose between vanilla, enhanced and aggresive AI, which btw not only for 1p mode but also for vs mode. 

Also they don't hit themselves, to make things worse for some reason some smart ass dev thought it was a great idea to let your teammates in Star Fox Team and Giant Remix attack themselves, not only your teammates being overly dumb but also weak as fuck but this difficulty increase is beyond ridiculous if even your partner can attack you whilst you fight a team of handicapped mobs that are hard to kill and kill you earlier and with the giant character it gets even worse.

**Comment by leodexe** [comment]
Long story short, what makes unbalanced the Remix 1P Mode is the fact that Team Attack is set to off when fighting multiple opponents such as Polygon Team. While your assigned teammate can friendly fire you and viceversa, this can have a huge impact as you do not control the actions of a Lv3 CPU that could randomly put you into a losing scenario. While having to fight 30 polygons while team attack is off.

You guys seriously playtested and approved this?

**Comment by PDCaptain** [comment]
I think the difficulty is fine. It's supposed to be a challenge for veteran players. Go ahead and increase the difficulty, if anything.
